### PR TITLE
#167735029 Setup swagger documentation

### PR DESCRIPTION
**Pull request by prieste**
[starts #167735029]

## If implemented this pr should:
    Setup documentation using SwaggerUi

 ## Description 
   Setup documentation for current functioning routes

## To test pr
   Start server using  "npm start"
   navigate to "localhost:3000/docs" on your browser

## Pivotal tracker stories
#167735029

### CODE REVIEW

**Comment by Annmary12** [comment]
@prieste, kindly resolve conflicts on your PR and also follow the proper PR description.

**Comment by prieste** [comment]
> @prieste, kindly resolve conflicts on your PR and also follow the proper PR description.

Hi @Annmary12 some of the conflicts are on the package.json.lock file I am a bit weary of manually manipulating this file, I did try following the proper format for the PR, pointers as to what I am doing wrong will be appreciatiated

**Comment by prieste** [comment]
> > @prieste, kindly resolve conflicts on your PR and also follow the proper PR description.
> 
> Hi @Annmary12 some of the conflicts are on the package.json.lock file I am a bit weary of manually manipulating this file, I did try following the proper format for the PR, pointers as to what I am doing wrong will be appreciatiated

**Comment by Annmary12** [comment]
> > @prieste, kindly resolve conflicts on your PR and also follow the proper PR description.
> 
> Hi @Annmary12 some of the conflicts are on the package.json.lock file I am a bit weary of manually manipulating this file, I did try following the proper format for the PR, pointers as to what I am doing wrong will be appreciatiated

@prieste, what do you mean by manually manipulating of the file?
Also, I created a PR template which I asked you guys to follow. You can check this PR for an example: https://github.com/andela/iceman-backend/pull/4

**Pull request closed without merging**
